import os
import time
print ("...")
time.sleep(3)
print ("...")
time.sleep(3)
print ("...")
time.sleep(3)
print ("...")
time.sleep(6)
print("Welcome to Fury Networks OS!")
time.sleep(3)
print ("   ")
time.sleep(3)
print ("   ")
time.sleep(3)
print ("   ")
time.sleep(6)
print ("To get started, press F2 to enter BIOS,")
time.sleep(3)
print ("or press F12 to boot system")
time.sleep(10)
print ("   ")
