import time
print("|      |")
print("|      |")
print("--------")
print("|      |")
print("|      |")
print("  ")
time.sleep(1)
print("  ")
print("|-------")
print("|       ")
print("|-------")
print("|       ")
print("|-------")
print("  ")
time.sleep(1)
print("  ")
print("|")
print("|")
print("|")
print("|")
print("--------")
print("  ")
time.sleep(1)
print("  ")
print("|")
print("|")
print("|")
print("|")
print("--------")
print("  ")
time.sleep(1)
print("  ")
print("--------")
print("|      |")
print("|      |")
print("|      |")
print("--------")
time.sleep(3)
print("FURY NETWORKS OS")
time.sleep(5)
print("WAITING FOR BOOT PROCESSES.....")
time.sleep(3)
print(".....")
time.sleep(3)
print(".....")
time.sleep(5)
print("PRESS F1 TO BOOT PROCESSES")
